apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: atlantis
    app.kubernetes.io/managed-by: Helm
  name: atlantis
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: atlantis
  type: NodePort
status:
  loadBalancer: {}