apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: atlantis-scaler
  labels:
    app: atlantis-scaler
spec:
  maxReplicaCount: 5
  minReplicaCount: 1
  pollingInterval: 15
  scaleTargetRef:
    name: atlantis
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://atlantis-prometheus-server:80
        metricName: cpu_usage
        query: sum(irate(process_cpu_seconds_total{app="atlantis"}[2m])) * 100
        threshold: '50'
